spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=vcap.services.postgres_credentials.credentials.host
spring.datasource.username=vcap.services.postgres_credentials.credentials.username
spring.datasource.password=vcap.services.postgres_credentials.credentials.password

hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=create-drop