name: build and deploy pipeline for managementapi


on:
  push:
    branches:
      - 'develop'
      - 'master'
    paths:
      - 'application-apis/managementapi/**'
      - 'application-models/**'
      - 'application-queuecommunication/**'
  pull_request:
    branches: 
      - 'master'
    paths:
      - 'application-apis/managementapi/**'
      - 'application-models/**'
      - 'application-queuecommunication/**'
  release:
    types:
      - created
  
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    # Build your app here
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
      - name: Install with Maven
        run: mvn install -DskipTests
      - name: Maven Verify with SonarScan
        run: mvn -B clean verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: cloud foundry for managementapi project
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_LOGIN }}
          cf_password: ${{ secrets.CF_PASS }}
          cf_org: CCC
          cf_space: AMOS-EDI
          command: push managementapi-amos
