name: Push Projekt to Cloud Foundry


on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    # Build your app here

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: https://api.my-cloud-foundry.com
        cf_username: lyegeniy@googlemail.com
        cf_password: 8BMUVjC.v.nH&uH
        cf_org: Honeybadger
        cf_space: development
        command: push -f manifest.yml